name: TLPQuickLook
options:
  bundleIdPrefix: com.tiledlayout
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"

packages:
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation
    from: "0.9.19"

settings:
  base:
    SWIFT_VERSION: "5.9"
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Automatic

fileGroups:
  - Shared

targets:
  TLPQuickLook:
    type: application
    platform: macOS
    sources:
      - path: TLPQuickLookApp
    dependencies:
      - target: TLPThumbnail
        embed: true
      - target: TLPPreview
        embed: true
    entitlements:
      path: TLPQuickLookApp/TLPQuickLook.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-only: true
    info:
      path: TLPQuickLookApp/Info.plist
      properties:
        CFBundleDisplayName: TLP QuickLook
        CFBundleIdentifier: com.tiledlayout.quicklook
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        LSMinimumSystemVersion: "14.0"
        LSUIElement: true
        CFBundleDocumentTypes:
          - CFBundleTypeName: Tiled Layout Package
            CFBundleTypeRole: Viewer
            LSHandlerRank: Default
            LSItemContentTypes:
              - com.tiledlayout.tlp
        UTExportedTypeDeclarations:
          - UTTypeIdentifier: com.tiledlayout.tlp
            UTTypeDescription: Tiled Layout Package
            UTTypeConformsTo:
              - com.pkware.zip-archive
              - public.data
            UTTypeTagSpecification:
              public.filename-extension:
                - tlp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.tiledlayout.quicklook
      INFOPLIST_FILE: TLPQuickLookApp/Info.plist
      GENERATE_INFOPLIST_FILE: false

  TLPThumbnail:
    type: app-extension
    platform: macOS
    sources:
      - path: TLPThumbnail
      - path: Shared
    dependencies:
      - package: ZIPFoundation
    entitlements:
      path: TLPThumbnail/TLPThumbnail.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-only: true
    info:
      path: TLPThumbnail/Info.plist
      properties:
        CFBundleDisplayName: TLP Thumbnail
        CFBundleIdentifier: com.tiledlayout.app.thumbnail
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        LSMinimumSystemVersion: "14.0"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.quicklook.thumbnail
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ThumbnailProvider
          NSExtensionAttributes:
            QLSupportedContentTypes:
              - com.tiledlayout.tlp
            QLSupportsSearchableItems: false
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.tiledlayout.app.thumbnail
      INFOPLIST_FILE: TLPThumbnail/Info.plist
      GENERATE_INFOPLIST_FILE: false

  TLPPreview:
    type: app-extension
    platform: macOS
    sources:
      - path: TLPPreview
      - path: Shared
    dependencies:
      - package: ZIPFoundation
    entitlements:
      path: TLPPreview/TLPPreview.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-only: true
    info:
      path: TLPPreview/Info.plist
      properties:
        CFBundleDisplayName: TLP Preview
        CFBundleIdentifier: com.tiledlayout.app.preview
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        LSMinimumSystemVersion: "14.0"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.quicklook.preview
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).PreviewViewController
          NSExtensionAttributes:
            QLSupportedContentTypes:
              - com.tiledlayout.tlp
            QLSupportsSearchableItems: false
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.tiledlayout.app.preview
      INFOPLIST_FILE: TLPPreview/Info.plist
      GENERATE_INFOPLIST_FILE: false
